sudo: required
language: python
dist: xenial
python: 3.7

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install poetry
  - pip install black
  - poetry install -v

script:
  - make test
  - black --check .

after_success:
  - make

deploy:
  provider: releases
  api_key:
    secure: kcJSr3bNdARZxBXFWnxeKHeNXSFPpU+px/Kq/jOCISSapbkTYeXB/lWczOR/z3O//U7rFCNJXAu0sfwQ2SwkakDDRehiDXNAAn/GBa4J/Iph0sCiWjw/dvyIIbwlKHYfw4zanVCZqyaCHERuFW4+JKrybT7mwACrJGtsyiJeabP3diWR+MdNZdLe9/vB5yelU+ysoQe8TvSPL08j6NciJasN/GhMxfmiAIAatEEIrGS3h0qxPhhcwIk9vn9WAQ4Cu+2cpUPTxtTec1odUDo/GtXpkkP0odo7V+wlm22kCjxikZYmhII4kbcuDe6ZtstXJglGDwmd3aAtp52OFw6fgEuWZE1MNLE+fGaX2wznLZMXOYgfpDzMSJ/ucSJA++TNLDMGB8ir+Hemv3UdeIHVuuX0W0xLOpYHNBOUn6dQXKxNAjCf74Ubn8Buk1Wzs7Gg6J1tJe8uor9x7HQVaeJ+rQo1vNUYpe665SFwjgoVtniQ1Cs2IOIPcbDddt35+5fXPmJYo25aS3tQ7Ut4rXqO4WogYg4VGnX95CME4g8I7LBA/Xe95LDLOG4LKOPzm0XID570G4mQm4Uxhhi355d3b9MpfRvjSO8HJLg3IEi5WkkMQFBLpshno9mdud6BfvDr1qNBtOkcKDoxjTINe42FxpmX7qmd5ftEZvAvWac6Pcs=
  file: orts-linux64.zip
  skip_cleanup: true
  on:
    tags: true
