sudo: required
language: python
dist: xenial
python: 3.7

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

install:
  - pip install poetry
  - pip install black
  - poetry install -v

script:
  - make test
  - black --check .

after_success:
  - make
