environment:

  matrix:
    - PYTHON: 'C:\Python37-x64'

install:
  - '%PYTHON%\python.exe -m pip install --upgrade pip'
  - '%PYTHON%\python.exe -m pip install pyinstaller'

build: off

#test_script:
  #- 'ECHO 1'

after_test:
  - '%PYTHON%\Scripts\pyinstaller --onefile --noconsole orts.py'
  - 'Xcopy /S /I /E data dist\data'
  - 'Xcopy /S /I /E web dist\web'

artifacts:
  - path: dist
    name: orts-win64

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your artifacts from the Appveyor "artifacts" tab for your build.
