environment:

  matrix:
    - PYTHON: 'C:\Python37-x64'

install:
  - '%PYTHON%\python.exe -m pip install --upgrade pip'
  # For some reason if I let poetry install pyinstaller then pywin32 won't be installed
  # correctly. Trying `pip install pywin32 pywin32-ctypes` doesn't help either.
  # Therefore manual pip install for now.
  - '%PYTHON%\python.exe -m pip install pyinstaller requests pycountry'

build: off

#test_script:
  #- 'ECHO 1'

after_test:
  - '%PYTHON%\Scripts\pyinstaller --onefile --noconsole orts.py'
  - 'Xcopy /S /I /E data dist\data'
  - 'Xcopy /S /I /E web dist\web'

artifacts:
  - path: dist
    name: orts-win64

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: ''
  provider: GitHub
  auth_token:
    secure: G9x5d8uuXHQ2H0XLXtX4avPDhhwX7//MI6cM9QCTwE9VuuAWDjiKXz3uPgaMV5sG # encrypted
  draft: false
  prerelease: false
  force_update: true # in case travis released linux build first
  on:
    APPVEYOR_REPO_TAG: true # deploy on tag push only
